# Generated by Django 4.2.11 on 2024-03-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce', '0007_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='home_adress',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
